version: '3'

services:
  catalog:
    build: ./catalog
    ports:
      - "5000:5000"
    volumes:
      - ./catalog/data:/app/data
    networks:
      - bazar-network

  order:
    build: ./order
    ports:
      - "5001:5001"
    volumes:
      - ./order/data:/app/data
    depends_on:
      - catalog
    networks:
      - bazar-network

  frontend:
    build: ./frontend
    ports:
      - "5002:5002"
    depends_on:
      - catalog
      - order
    networks:
      - bazar-network

networks:
  bazar-network:
    driver: bridge